### ISSUE TITLE
Feature: continue game

### ISSUE THREAD

**Issue by Igmat** [Igmat/SpaceExpatriateReact#32]
Save game state in localStorage.
## Subtasks
- [X] determine: what to save (& what do we save during the round)
   - [X] game
      - [X] round
      - [X] points
      - [X] cards in hand
      - [X] cards on the table
      - [X] opened cards
      - [X] garbage resources
   - [X] round
      - [X] permanent reset 
      - [X] player resources
      - [X] selected mission
      - [X] energy
      - [X] phase
- [X] mobx-localstorage & autorun

**Comment by KiraSeletska** [comment]
!

**Comment by Igmat** [comment]
Added by #52
