### ISSUE TITLE
Colony mechanic

### ISSUE THREAD

**Issue by Igmat** [Igmat/SpaceExpatriateReact#63]
На 17-ой странице [правил](https://alkhwarizmi.games/downloads/se-rulebook.pdf) начинается перечень всех карт колоний. Действие для получения колоний (терраформинг) у нас уже реализовано. Нужно понять как всю эту механику мы добавим в игру:

## Tasks:
- [X] Описать карты 
- [X] Создать отдельный интерфейс для карты колоний
- [X] Создать функцию createCards (создается колода) (Anastasia)
- [X] Создать DeckModel -> ColonyModel (Maria)
    - mixCard + openCard(3 штуки) + takeCard
- [X] - сделать место для колоний на столе (Kira)
- [x] - доделать постройку колоний ** (Anastasia) **
    - [X] - tryBuildColony проверка на собледение условий
    - [X] - reset - если передумал и выбрал не те карты
    - [X] - builColony метод takeOpenedCard с методом постройки колонии (перемещении карты колонии на стол к игроку) 
- [x] Создать новый менеджер для колоний (Maria)
- [x] Добавить метод проверки карт колоний на столе при новом раунде: ** (Maria) **
    - [X] - добавить новые карты в Board если карт меньше чем 3 на момент нового раунда (Anastasia)// я увлеклась
    - [X] - сейчас колода, елси закончилась, снова генериться (Anastasia) (оно локалом починилось).
    - [x] - добавить по одному пойнту на неиспользованные карты
- [X] - добавить построеные и открытые колонии в локал сторадж
- [ ] - isSelected: доработать таким образом, чтобы можно было при повторном клике на выбранную карту убрать обводку и убрать саму карту из масива выбранных карт (Anastasia)
- [ ] - isDisabled (после мерджа ветки с isDisabled) - усоврешенсвованный метод, который не дает выбирать не ту комбинацию карт(Anastasia)

### Colony in action:
 - [ ] - Delivery
       - [ ] - BLACK MARKET
       - [ ] - "SPACE LIFT"
 - [ ] - Engeneering
       - [ ] - "SPACECRAFT MANUFACTORY"
       - [ ] - "SPACE INDUSTRY CENTER"
       - [ ] - "HELIOSTAT DESERT",
 - [ ] - Terraforming
       - [ ] - "OPERATIONS SUPPORT COMMAND",
       - [ ] - "STRATEGIC DEVELOPMENT CENTER",
       - [ ] - "FIELD RESEARCH HEADQUARTERS",

вопросы:
1) назрена нам здесь кнопка Confirm которая делает то же, что и End Turn и End Round?
2) сколько колоний за ход может построить 1 игрок?
